apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: croptrace
data:
  APP_ENV: "production"
  API_PORT: "8000"
  DB_HOST: "postgres-0.postgres-headless.croptrace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "croptrace"
