apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: croptrace
type: Opaque
stringData:
  DB_USER: "croptrace_user"
  DB_PASSWORD: "password@123"
  MONOLITH_API_KEY: "mock-monolith-key-12345"
