name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build and Test
      working-directory: ./api
      run: |
        go mod tidy
        go build -v ./...

    - name: Determine Image Tag
      id: tag
      run: |
        VERSION=$(jq -r .version api/version.json)
        SHORT_SHA=${GITHUB_SHA::7}
        echo "image_tag=${VERSION}-${SHORT_SHA}" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: true
        tags: sachithram/croptracetelemetry:${{ steps.tag.outputs.image_tag }}

  deploy-to-local-kind:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: DEV
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.8.0

    - name: Update image tag with Kustomize
      working-directory: ./k8s/overlays/dev
      run: |
        kustomize edit set image docker.io/sachithram/croptracetelemetry=sachithram/croptracetelemetry:${{ needs.build-and-push.outputs.image_tag }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -k k8s/overlays/dev

    - name: Verify Deployment
      run: |
        kubectl get all -n croptrace
        kubectl rollout status deployment/croptrace-api -n croptrace --timeout=90s
